# help='model.pt path(s)'
weights: './configs/basic_config/last0231b.pt'
#weights: './configs/basic_config/lasts.pt'
img_size: 640
conf_thres: 0.8
iou_thres: 0.5
# help='cuda device, i.e. 0 or 0,1,2,3 or cpu'
device: '0'
view_img: True
print_result: False
# help='filter by class': '', 0 or [0,1,2]
classes: [0,1]
agnostic_nms: True
# 'augmented inference'
augment: True
# 'update all models'
update: False
